/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.staging.jsonc --include-runtime=false` (hash: 0a8bc3193d5a39ea6ad13bacd1befce7)
interface __BaseEnv_Env {
	DB: D1Database;
	JOB_QUEUE: Queue;
	ANALYSIS_PROFILE_ID: "fixed-sfen-staging-v1";
	ANALYSIS_PROFILE_VERSION: "1";
	ANALYSIS_MODEL_ID: "analysis-model-staging-v1";
	ANALYSIS_ENGINE_ID: "YaneuraOu NNUE 9.70git 64AVX2";
	ANALYSIS_INSTANCE_TYPE: "standard-2";
	ANALYSIS_CONTAINER: DurableObjectNamespace<import("./src/index").AnalysisContainer>;
	JOB_COORDINATOR: DurableObjectNamespace<import("./src/index").JobCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "AnalysisContainer" | "JobCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ANALYSIS_PROFILE_ID" | "ANALYSIS_PROFILE_VERSION" | "ANALYSIS_MODEL_ID" | "ANALYSIS_ENGINE_ID" | "ANALYSIS_INSTANCE_TYPE">> {}
}
